name: CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  q4-ynov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
        
    steps:
      - name: Testing simple_math.py
        run: python -m unittest simple_math.py